// Auto-generated by export_int.py - do not edit by hand
localparam integer M_CONV1     = 18644;
localparam integer SHIFT_CONV1 = 23;
localparam integer M_CONV2     = 31114;
localparam integer SHIFT_CONV2 = 23;
localparam integer M_FC1     = 23619;
localparam integer SHIFT_FC1 = 24;
